[CmdletBinding()]
param(
    [string]$EnvFile = "",
    [string]$RemoteHost = "",
    [string]$User = "",
    [string]$KeyPath = "",
    [int]$SshPort = 0,
    [string]$ProjectDir = "",
    [string]$RemoteUploadDir = "",
    [string]$LocalRepo = "",
    [ValidateSet("rsync", "bundle", "git", "none")][string]$SyncMethod = "",
    [string]$BundlePath = "",
    [string]$RepoUrl = "",
    [string]$RepoRef = "",
    [ValidateSet("replay", "live")][string]$RunMode = "",
    [string]$LocalLabBundle = "",
    [string]$RemoteLabBundle = "",
    [string]$RunStamp = "",
    [string]$SensorId = "",
    [string]$Interface = "",
    [switch]$EnableDashboard,
    [switch]$Help
)

Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot "oracle_common.ps1")

if ($Help) {
    @"
Usage:
  powershell -ExecutionPolicy Bypass -File scripts/oracle_remote_run.ps1 [-EnvFile <path>] [-RemoteHost <ip>] [-User <user>] [-KeyPath <path>] [-SshPort <port>] [-ProjectDir <path>] [-RemoteUploadDir <path>] [-LocalRepo <path>] [-SyncMethod <rsync|bundle|git|none>] [-BundlePath <path>] [-RepoUrl <url>] [-RepoRef <ref>] [-RunMode <replay|live>] [-LocalLabBundle <path>] [-RemoteLabBundle <path>] [-RunStamp <stamp>] [-SensorId <id>] [-Interface <name>] [-EnableDashboard]
"@ | Write-Host
    exit 0
}

$resolvedEnvFile = Get-OracleOptionalEnvFile -EnvFile $EnvFile
$settings = Import-OracleProjectEnv -EnvFile $resolvedEnvFile
$context = New-OracleSshContext -Settings $settings -RemoteHost $RemoteHost -RemoteUser $User -SshKeyPath $KeyPath -SshPort $SshPort -RemoteProjectDir $ProjectDir -RemoteUploadDir $RemoteUploadDir

if ([string]::IsNullOrWhiteSpace($LocalRepo)) {
    $LocalRepo = Get-OracleSetting -Settings $settings -Key "ORACLE_VM_LOCAL_REPO"
    if ([string]::IsNullOrWhiteSpace($LocalRepo)) {
        $LocalRepo = Get-OracleRepoRoot
    }
}
if ([string]::IsNullOrWhiteSpace($SyncMethod)) {
    $SyncMethod = Get-OracleSetting -Settings $settings -Key "ORACLE_VM_SYNC_METHOD" -DefaultValue "rsync"
}
if ([string]::IsNullOrWhiteSpace($RunMode)) {
    $RunMode = Get-OracleSetting -Settings $settings -Key "ORACLE_VM_RUN_MODE" -DefaultValue "replay"
}
if ([string]::IsNullOrWhiteSpace($SensorId)) {
    $SensorId = Get-OracleSetting -Settings $settings -Key "ORACLE_VM_SENSOR_ID" -DefaultValue "oracle-cloud"
}
if ([string]::IsNullOrWhiteSpace($LocalLabBundle)) {
    $LocalLabBundle = Get-OracleSetting -Settings $settings -Key "ORACLE_VM_LOCAL_LAB_BUNDLE"
}

$LocalRepo = Expand-OracleHomePath $LocalRepo
$BundlePath = Expand-OracleHomePath $BundlePath
$LocalLabBundle = Expand-OracleHomePath $LocalLabBundle

$autoGeneratedBundle = $null
$autoGeneratedLabArchive = ""
$effectiveSyncMethod = $SyncMethod.ToLowerInvariant()

switch ($effectiveSyncMethod) {
    "rsync" {
        if (-not (Get-Command rsync -ErrorAction SilentlyContinue)) {
            Write-OracleLog "rsync is not available locally; falling back to bounded deployment-bundle transfer."
            $effectiveSyncMethod = "bundle"
        }
    }
    "bundle" { }
    "git" { }
    "none" { }
    default {
        Throw-OracleError "Unsupported SyncMethod value: $SyncMethod"
    }
}

try {
    switch ($effectiveSyncMethod) {
        "rsync" {
            Assert-OracleDirectory $LocalRepo
            Test-OracleDeploymentInputs -RepoDir $LocalRepo

            $prepRemote = @'
set -euo pipefail
project_dir="$1"
remote_user="$2"
sudo -n true >/dev/null 2>&1
sudo install -d -m 755 "$project_dir"
sudo chown -R "$remote_user:$remote_user" "$project_dir"
'@
            Invoke-OracleRemoteScript -Context $context -ScriptBody $prepRemote -Arguments @($context.RemoteProjectDir, $context.RemoteUser)

            $remoteShell = "ssh.exe -o BatchMode=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -i `"$($context.SshKeyPath)`" -p $($context.SshPort)"
            $rsyncArgs = @("-az", "--partial", "--progress", "-e", $remoteShell)
            foreach ($item in Get-OracleDeploymentItems) {
                $rsyncArgs += (Join-Path $LocalRepo $item)
            }
            $rsyncArgs += "$($context.RemoteTarget):$($context.RemoteProjectDir)/"
            Invoke-OracleExternal -FilePath "rsync" -Arguments $rsyncArgs
        }
        "bundle" {
            if ([string]::IsNullOrWhiteSpace($BundlePath)) {
                $tempOutDir = Join-Path ([System.IO.Path]::GetTempPath()) "universal-nids-oracle-bundles"
                $autoGeneratedBundle = New-OracleDeploymentBundle -RepoDir $LocalRepo -OutDir $tempOutDir -BundleName ""
                $BundlePath = $autoGeneratedBundle.BundlePath
            }

            Assert-OracleFile $BundlePath
            $manifestPath = [System.IO.Path]::ChangeExtension($BundlePath, ".manifest.txt")
            $remoteBundlePath = "$($context.RemoteUploadDir)/$([System.IO.Path]::GetFileName($BundlePath))"

            $prepareUpload = @'
set -euo pipefail
upload_dir="$1"
project_dir="$2"
remote_user="$3"
sudo -n true >/dev/null 2>&1
install -d -m 755 "$upload_dir"
sudo install -d -m 755 "$project_dir"
sudo chown -R "$remote_user:$remote_user" "$project_dir"
'@
            Invoke-OracleRemoteScript -Context $context -ScriptBody $prepareUpload -Arguments @($context.RemoteUploadDir, $context.RemoteProjectDir, $context.RemoteUser)

            Invoke-OracleScp -Context $context -Arguments @($BundlePath, "$($context.RemoteTarget):$remoteBundlePath")
            if (Test-Path $manifestPath) {
                Invoke-OracleScp -Context $context -Arguments @($manifestPath, "$($context.RemoteTarget):$($context.RemoteUploadDir)/$([System.IO.Path]::GetFileName($manifestPath))")
            }

            $extractRemote = @'
set -euo pipefail
bundle_path="$1"
project_dir="$2"
remote_user="$3"
sudo -n true >/dev/null 2>&1
sudo tar -xzf "$bundle_path" -C "$project_dir"
sudo chown -R "$remote_user:$remote_user" "$project_dir"
'@
            Invoke-OracleRemoteScript -Context $context -ScriptBody $extractRemote -Arguments @($remoteBundlePath, $context.RemoteProjectDir, $context.RemoteUser)
        }
        "git" {
            Assert-OracleValue -Value $RepoUrl -Label "-RepoUrl"
            $gitRemote = @'
set -euo pipefail
repo_url="$1"
project_dir="$2"
repo_ref="$3"
sudo -n true >/dev/null 2>&1
sudo install -d -m 755 "$project_dir"
sudo chown "$USER:$USER" "$project_dir"
if [[ -d "$project_dir/.git" ]]; then
  git -C "$project_dir" fetch --all --tags
else
  git clone "$repo_url" "$project_dir"
fi
if [[ -n "$repo_ref" ]]; then
  git -C "$project_dir" checkout "$repo_ref"
  git -C "$project_dir" pull --ff-only origin "$repo_ref" || true
else
  git -C "$project_dir" pull --ff-only || true
fi
'@
            Invoke-OracleRemoteScript -Context $context -ScriptBody $gitRemote -Arguments @($RepoUrl, $context.RemoteProjectDir, $RepoRef)
        }
        "none" { }
    }

    $prepareRuntime = @'
set -euo pipefail
project_dir="$1"
cloud_root="$2"
live_interface="$3"
compose_file="$project_dir/docker-compose.cloud-single-node.yml"
env_file="$project_dir/.env"
example_file="$project_dir/.env.example"

test -f "$compose_file"
test -f "$example_file"
test -f "$project_dir/Dockerfile"
test -f "$project_dir/config/nids_cloud_single_node.yml"
test -f "$project_dir/scripts/cloud_validation_workflow.py"
test -d "$project_dir/src"

if [[ ! -f "$env_file" ]]; then
  cp "$example_file" "$env_file"
fi

upsert_env() {
  key="$1"
  value="$2"
  file="$3"
  if grep -q "^${key}=" "$file"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    printf "%s=%s\n" "$key" "$value" >>"$file"
  fi
}

upsert_env "NIDS_CONFIG_PATH" "config/nids_cloud_single_node.yml" "$env_file"
upsert_env "NIDS_CLOUD_RUNTIME_OUTPUT_DIR" "$cloud_root/runtime/output" "$env_file"
upsert_env "NIDS_CLOUD_RUNTIME_LOG_DIR" "$cloud_root/runtime/logs" "$env_file"
upsert_env "NIDS_CLOUD_RUNTIME_REPORTS_DIR" "$cloud_root/runtime/reports" "$env_file"
upsert_env "NIDS_CLOUD_RUNTIME_ARTIFACTS_DIR" "$cloud_root/runtime/artifacts" "$env_file"
upsert_env "NIDS_CLOUD_LAB_BUNDLES_DIR" "$cloud_root/lab_generated/bundles" "$env_file"
upsert_env "NIDS_CLOUD_REPLAY_DIR" "$cloud_root/replay/staging" "$env_file"
if [[ -n "$live_interface" ]]; then
  upsert_env "NIDS_INTERFACE" "$live_interface" "$env_file"
fi

layout_paths=(
  "$cloud_root/runtime/output"
  "$cloud_root/runtime/logs"
  "$cloud_root/runtime/reports"
  "$cloud_root/runtime/artifacts/incoming"
  "$cloud_root/runtime/artifacts/processed"
  "$cloud_root/runtime/artifacts/quarantine"
  "$cloud_root/lab_generated/bundles"
  "$cloud_root/lab_generated/archive"
  "$cloud_root/replay/staging"
  "$cloud_root/archive/output_bundles"
  "$cloud_root/manifests"
  "$project_dir/tmp/oracle-uploaded-bundles"
)
for path_item in "${layout_paths[@]}"; do
  install -d -m 755 "$path_item"
done

sudo docker version >/dev/null 2>&1
if sudo docker compose version >/dev/null 2>&1; then
  sudo docker compose --project-directory "$project_dir" --env-file "$env_file" -f "$compose_file" config >/dev/null
else
  sudo docker-compose --project-directory "$project_dir" --env-file "$env_file" -f "$compose_file" config >/dev/null
fi
'@
    Invoke-OracleRemoteScript -Context $context -ScriptBody $prepareRuntime -Arguments @($context.RemoteProjectDir, $context.RemoteCloudDataDir, $Interface)

    if ($RunMode -eq "live") {
        Assert-OracleValue -Value $Interface -Label "-Interface"
        $liveRemote = @'
set -euo pipefail
project_dir="$1"
enable_dashboard="$2"
compose_file="$project_dir/docker-compose.cloud-single-node.yml"
env_file="$project_dir/.env"
if sudo docker compose version >/dev/null 2>&1; then
  compose_base=(sudo docker compose --project-directory "$project_dir" --env-file "$env_file" -f "$compose_file")
else
  compose_base=(sudo docker-compose --project-directory "$project_dir" --env-file "$env_file" -f "$compose_file")
fi
"${compose_base[@]}" build nids-runtime
"${compose_base[@]}" up -d nids-runtime
if [[ "$enable_dashboard" == "1" ]]; then
  "${compose_base[@]}" --profile dashboard up -d nids-dashboard
fi
"${compose_base[@]}" ps
printf "runtime_output_dir=%s\n" "$project_dir/cloud_data/runtime/output"
printf "runtime_logs_dir=%s\n" "$project_dir/cloud_data/runtime/logs"
printf "runtime_reports_dir=%s\n" "$project_dir/cloud_data/runtime/reports"
'@
        Invoke-OracleRemoteScript -Context $context -ScriptBody $liveRemote -Arguments @($context.RemoteProjectDir, ($(if ($EnableDashboard) { "1" } else { "0" })))
        exit 0
    }

    if ($RunMode -ne "replay") {
        Throw-OracleError "Unsupported RunMode value: $RunMode"
    }

    if (-not [string]::IsNullOrWhiteSpace($LocalLabBundle)) {
        Assert-OracleDirectory $LocalLabBundle
        if ([string]::IsNullOrWhiteSpace($RunStamp)) {
            $RunStamp = Get-OracleTimestampUtc
        }
        $resolvedLocalLabBundle = (Resolve-Path $LocalLabBundle).Path
        $remoteLabBundleBase = [System.IO.Path]::GetFileName($resolvedLocalLabBundle)
        $RemoteLabBundle = "$($context.RemoteBundleTempDir)/$remoteLabBundleBase-$RunStamp"
        $autoGeneratedLabArchive = Join-Path ([System.IO.Path]::GetTempPath()) "oracle-lab-bundle-$RunStamp.tar.gz"
        Invoke-OracleExternal -FilePath "tar.exe" -Arguments @(
            "-czf",
            $autoGeneratedLabArchive,
            "-C",
            (Split-Path -Parent $resolvedLocalLabBundle),
            (Split-Path -Leaf $resolvedLocalLabBundle)
        )
        $remoteLabArchive = "$($context.RemoteUploadDir)/$([System.IO.Path]::GetFileName($autoGeneratedLabArchive))"

        $prepareLabUpload = @'
set -euo pipefail
upload_dir="$1"
bundle_dir="$2"
install -d -m 755 "$upload_dir"
install -d -m 755 "$(dirname "$bundle_dir")"
'@
        Invoke-OracleRemoteScript -Context $context -ScriptBody $prepareLabUpload -Arguments @($context.RemoteUploadDir, $RemoteLabBundle)
        Invoke-OracleScp -Context $context -Arguments @($autoGeneratedLabArchive, "$($context.RemoteTarget):$remoteLabArchive")

$extractLabUpload = @'
set -euo pipefail
archive_path="$1"
bundle_dir="$2"
if [[ -e "$bundle_dir" ]]; then
  echo "Remote lab bundle path already exists: $bundle_dir" >&2
  exit 1
fi
install -d -m 755 "$bundle_dir"
tar -xzf "$archive_path" -C "$bundle_dir" --strip-components=1
'@
        Invoke-OracleRemoteScript -Context $context -ScriptBody $extractLabUpload -Arguments @($remoteLabArchive, $RemoteLabBundle)
    }

    Assert-OracleValue -Value $RemoteLabBundle -Label "-LocalLabBundle or -RemoteLabBundle"
    if ([string]::IsNullOrWhiteSpace($RunStamp)) {
        $RunStamp = Get-OracleTimestampUtc
    }

    $replayRemote = @'
set -euo pipefail
project_dir="$1"
cloud_root="$2"
bundle_dir="$3"
run_stamp="$4"
sensor_id="$5"
compose_file="$project_dir/docker-compose.cloud-single-node.yml"
env_file="$project_dir/.env"

if sudo docker compose version >/dev/null 2>&1; then
  compose_base=(sudo docker compose --project-directory "$project_dir" --env-file "$env_file" -f "$compose_file")
else
  compose_base=(sudo docker-compose --project-directory "$project_dir" --env-file "$env_file" -f "$compose_file")
fi
"${compose_base[@]}" build nids-runtime

plan_json="$(cd "$project_dir" && python3 scripts/cloud_validation_workflow.py stage-bundle --root "$cloud_root" --bundle-dir "$bundle_dir" --sensor-id "$sensor_id" --run-stamp "$run_stamp")"
printf "%s" "$plan_json" >"$cloud_root/manifests/oracle_latest_plan.json"

mapfile -t plan_fields < <(printf "%s" "$plan_json" | python3 -c 'import json, sys; payload=json.load(sys.stdin); print(payload["staged_bundle_dir"]); print(payload["pcap_path"]); print(payload["labels_path"]); print(payload["runtime_output_dir"]); print(payload["reports_dir"]); print(payload["plan_path"])')
staged_bundle_dir="${plan_fields[0]}"
pcap_path="${plan_fields[1]}"
labels_path="${plan_fields[2]}"
runtime_output_dir="${plan_fields[3]}"
reports_dir="${plan_fields[4]}"
plan_path="${plan_fields[5]}"
run_name="$(basename "$runtime_output_dir")"
combined_log_path="$cloud_root/runtime/logs/${run_name}.docker-run.log"

set -o pipefail
"${compose_base[@]}" run --rm \
  -e "NIDS_PCAP_DIR=/data/replay/staging/$(basename "$staged_bundle_dir")/$(basename "$pcap_path")" \
  -e "NIDS_LABELS_PATH=/data/replay/staging/$(basename "$staged_bundle_dir")/$(basename "$labels_path")" \
  -e "NIDS_OUTPUT_DIR=/data/runtime/output/$run_name" \
  -e "NIDS_SENSOR_ID=${sensor_id}-${run_stamp}" \
  nids-runtime 2>&1 | tee "$combined_log_path"

"${compose_base[@]}" run --rm nids-runtime \
  python -m nids report \
  --from-db "/data/runtime/output/$run_name/nids.db" \
  --out "/data/runtime/reports/$run_name/summary.md"

"${compose_base[@]}" run --rm nids-runtime \
  python -m nids visualize \
  --from-db "/data/runtime/output/$run_name/nids.db" \
  --out "/data/runtime/reports/$run_name/graphs"

"${compose_base[@]}" ps -a || true
printf "run_name=%s\n" "$run_name"
printf "plan_path=%s\n" "$plan_path"
printf "runtime_output_dir=%s\n" "$runtime_output_dir"
printf "runtime_reports_dir=%s\n" "$reports_dir"
printf "runtime_log_path=%s\n" "$combined_log_path"
'@
    Invoke-OracleRemoteScript -Context $context -ScriptBody $replayRemote -Arguments @($context.RemoteProjectDir, $context.RemoteCloudDataDir, $RemoteLabBundle, $RunStamp, $SensorId)
}
finally {
    if ($null -ne $autoGeneratedBundle) {
        Remove-Item -Path $autoGeneratedBundle.BundlePath -Force -ErrorAction SilentlyContinue
        Remove-Item -Path $autoGeneratedBundle.ManifestPath -Force -ErrorAction SilentlyContinue
    }
    if (-not [string]::IsNullOrWhiteSpace($autoGeneratedLabArchive)) {
        Remove-Item -Path $autoGeneratedLabArchive -Force -ErrorAction SilentlyContinue
    }
}
